### ISSUE TITLE
Unable to install webpack because of @webassemblyjs and @xtuc depedencies

### ISSUE THREAD

**Issue by dprosper** [xtuc/webassemblyjs#462] opened 2018-10-08 23:31 UTC
Please refer to this issue: https://github.com/webpack/webpack/issues/8159 for more details.

**Comment by xtuc** [comment] 2018-10-09 11:43
Are you using a npm proxy or cache?

**Comment by dprosper** [comment] 2018-10-09 12:43
no proxy, cache (not really sure?).  Interestingly on the exact same network it works on my Mac.  Not on the PC.

**Comment by dprosper** [comment] 2018-10-09 13:52
I looked up the options for npm cache, I ended up running this command: 

`npm cache clean --force`

however, that did not make a difference.  after it completed the same error when trying to add webpack.

**Comment by dprosper** [comment] 2018-10-09 14:09
here is a npm log, if that helps any....

[2018-10-09T14_03_51_620Z-debug.log](https://github.com/xtuc/webassemblyjs/files/2460729/2018-10-09T14_03_51_620Z-debug.log)

**Comment by xtuc** [comment] 2018-10-09 15:42
Seems that the issue is on your side.

**Comment by dprosper** [comment] 2018-10-09 15:43
seriously ?? any hints, why do you believe that to be the case? all other NPM pacakages are installed without any issues...

**Comment by xtuc** [comment] 2018-10-09 15:46
You are the only one that reported this issue, and on my side it works fine. I can't much more?

**Comment by fzxt** [comment] 2018-10-09 22:16
I am running into this as well.

**Comment by xtuc** [comment] 2018-10-11 06:10
Ok, @adriano515 @fzxt are you a npm proxy or cache?

**Comment by xtuc** [comment] 2018-10-11 06:11
I already reached out npm for a similar issue recently, I can ping them again for this one.

**Comment by fzxt** [comment] 2018-10-11 16:11
@xtuc I resolved this by commenting out all contents in my npmrc. It had reference to a proxy.

**Comment by adriano515** [comment] 2018-10-11 21:31
im using cache

**Comment by dannycurrie** [comment] 2018-11-16 12:04
I also ran into this issue.

[As others have noticed](https://github.com/dcodeIO/long.js/issues/73#issuecomment-436964461), it appears to be related to the contents of the .npmrc file...

- Commenting out the contents of my .npmrc
- Running yarn install
- readding .npmrc contents

... worked for me

**Comment by dariobanfi** [comment] 2018-11-22 16:30
Same issue here. The strange thing is that it works on my local computer, but not on the CI pipeline!

**Comment by janbaykara** [comment] 2018-11-28 18:46
Same issue!

**Comment by germanamz** [comment] 2018-11-28 19:10
This are the yarn errors this packages: **@webassemblyjs/ast @webassemblyjs/helper-module-context @webassemblyjs/wasm-edit @webassemblyjs/wasm-parser** 

------------------------------------------------------------------------------------------

/$ yarn add @webassemblyjs/ast -d
yarn add v1.3.2
info No lockfile found.
[1/4] 🔍  Resolving packages...
error Couldn't find package "@webassemblyjs/ast" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

/$ yarn add  @webassemblyjs/helper-module-context -d
yarn add v1.3.2
info No lockfile found.
[1/4] 🔍  Resolving packages...
error Couldn't find package "@webassemblyjs/helper-module-context" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

/$ yarn add @webassemblyjs/wasm-edit -d
yarn add v1.3.2
info No lockfile found.
[1/4] 🔍  Resolving packages...
error Couldn't find package "@webassemblyjs/wasm-edit" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

/$ yarn add @webassemblyjs/wasm-parser -d
yarn add v1.3.2
info No lockfile found.
[1/4] 🔍  Resolving packages...
error Couldn't find package "@webassemblyjs/wasm-parser" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
------------------------------------------------------------------------------------------

The issue maybe on the npm scope of the organization or the packages...

**Comment by germanamz** [comment] 2018-11-28 20:16
Check https://github.com/webpack/webpack/issues/8434#issuecomment-442579651

**Comment by xtuc** [comment] 2019-04-03 13:25
I'm closing this issue for now since there's no activity, feel free to comment here and I will re-open it.

**Closed** 2019-04-03 13:26 UTC

**Comment by atdiff** [comment] 2019-07-05 20:29
@xtuc , this definitely seems to be a bigger npm issue. A few other npm packages are experiencing this as well.
Need to get more traction on this issue here - https://npm.community/t/always-reproducible-maximum-call-stack-size-exceeded-npm-install-error/1645/23

**Comment by Ptival** [comment] 2020-08-06 09:49
I just encountered this issue, and I don't even have a `.npmrc`.

Note that when I visit:
https://registry.npmjs.org/@xtuc%2flong

It says: `Not found`

**Comment by dstockhofe** [comment] 2020-08-06 09:49
Same issue here :-/

**Comment by veber88** [comment] 2020-08-06 09:50
Trouble with registry. It's a reason to have additional registry.

**Comment by bgausden** [comment] 2020-08-06 10:06
Fixed for me by running `npm login` on the command-line.

**Comment by xtuc** [comment] 2020-08-06 10:07
There's an ongoing npm incident https://status.npmjs.org/incidents/cksjqc1w11v5.

**Comment by kmuthukumar23** [comment] 2020-08-06 10:51
Same issue here :-(

**Comment by rfrancois** [comment] 2020-08-06 10:52
Same issue. https://registry.npmjs.org/@xtuc%2flong  returns 404.

**Comment by xtuc** [comment] 2020-08-06 10:56
This is due to an ongoing npm incident https://status.npmjs.org/incidents/cksjqc1w11v5.
